### PR TITLE
The cutMeshPlane function only works on triangular meshes. 

### PR DESCRIPTION
**Pull request by dmurdoch**
This gives an informative error.  See https://stackoverflow.com/q/68395692/2554330 for motivation.

### CODE REVIEW

**Comment by zarquon42b** [comment]
Hi, thanks for the PR. The alternative would be to convert the mesh to a triangular mesh using Morpho::quad2trimesh and issue a warning. Would you deem that useful?

**Comment by dmurdoch** [comment]
Yes, that would be a good change:  in fact, I'm in the middle of exporting `as.tmesh3d` from `rgl`, as I didn't notice `quad2trimesh`.  Differences between them:  

 - you have the `updateNormals` argument, mine just inherits the old normals; 
 - mine optionally drops the fairly new segment and point components.
 - mine is generic, passing non mesh objects to `as.mesh3d` first.

I think I'll still go ahead with `as.tmesh3d` since it's a pretty simple function, but it also makes sense for you to make use of `quad2trimesh` in `rmVertex`.  I'd encourage you to think about what to do with segments and points.

**Comment by zarquon42b** [comment]
Hi,
I think I will make `rmVertex` compatible with tmesh3d. There is a lot of legacy code in Morpho which I keep to avoid inconsistencies in research code. I'll have a look and if `as.tmesh3d` does the same I might just make `quad2trimesh` a wrapper for this.
I'll also look into the segments and points in rgl. I have neglected this as my personal research only deals with triangular meshes, so there is some coder bias ;)

**Comment by zarquon42b** [comment]
OK, `rmVertex` and therefore `cutMeshPlane` now work on tmesh3d. See 99e570892f51314cee523e50adc3b28e669036fb

**Pull request closed without merging**
